ProgramadorFajuto.View/Controllers/FerramentasController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using ProgramadorFajuto.Aplicacao.Modelos;
using ProgramadorFajuto.Aplicacao.Servicos;
using ProgramadorFajuto.View.CustomExtensions;
using System;

namespace ProgramadorFajuto.View.Controllers
{
    public class FerramentasController : Controller
    {
        private IHostingEnvironment _environment;
        private IServicoDeFormatacaoDeEmailMarketing _servicoDeFormatacaoDeEmailMarketing;

        public FerramentasController(IHostingEnvironment environment, IServicoDeFormatacaoDeEmailMarketing servicoDeFormatacaoDeEmailMarketing)
        {
            this._environment = environment;
            this._servicoDeFormatacaoDeEmailMarketing = servicoDeFormatacaoDeEmailMarketing;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult FormatadorDeEmailMarketing()
        {
            return View();
        }

        [HttpPost]
        public IActionResult FormatadorDeEmailMarketing(ModeloDeFormatadorDeEmailMarketing modelo)
        {
            if (modelo.BackgroundColor == null || modelo.Color == null || modelo.File == null || modelo.FontFamily == null || modelo.FontWeight == null)
            {
                this.AdicionarMensagemDeErro("Algum dado do formulário está nulo. Você está brincando com minha cara?");
                return View();
            }

            return File(this._servicoDeFormatacaoDeEmailMarketing.FormatarEmailMarketing(modelo), "application/file", "EmailFormatado.html");
        }
    }
}

ProgramadorFajuto.View/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProgramadorFajuto.View.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

ProgramadorFajuto.View/Controllers/PostsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProgramadorFajuto.View.Controllers
{
    public class PostsController : Controller
    {
        public IActionResult ComoRecortarEmailMarketing()
        {
            return View();
        }
    }
}

ProgramadorFajuto.View/Views/Ferramentas/FormatadorDeEmailMarketing.cshtml
@{
    ViewData["Title"] = "FormatadorDeEmailMarketing";
}

<section>
    <div class="container">
        <form method="post" asp-action="FormatadorDeEmailMarketing" asp-controller="Ferramentas" enctype="multipart/form-data" class="form-horizontal">
            <div class="form-group">
                <label for="color" class="col-lg-4 control-label">Cor do texto dinâmico:</label>
                <div class="col-lg-8">
                    <input type="text" name="color" />
                </div>
            </div>
            <div class="form-group">
                <label for="backgroundColor" class="col-lg-4 control-label">Cor do background do texto dinâmico:</label>
                <div class="col-lg-8">
                    <input type="text" name="backgroundColor" />
                </div>
            </div>
            <div class="form-group">
                <label for="fontWeight" class="col-lg-4 control-label">Font-Weight do texto dinâmico:</label>
                <div class="col-lg-8">
                    <input type="text" name="fontWeight" />
                </div>
            </div>
            <div class="form-group">
                <label for="fontFamily" class="col-lg-4 control-label">Font-Family do texto dinâmico:</label>
                <div class="col-lg-8">
                    <input type="text" name="fontFamily" />
                </div>
            </div>
            <div class="form-group">
                <label for="fontFamily" class="col-lg-4 control-label">Upload do arquivo .html</label>
                <div class="col-lg-8">
                    <input type="file" name="file" multiple />
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-8">
                    <button type="submit" class="btn btn-primary center-block">Formatar Arquivo</button>
                </div>
            </div>
        </form>
    </div>
</section>

ProgramadorFajuto.View/Views/Ferramentas/Index.cshtml
@{
    ViewData["Title"] = "Ferramentas";
}

<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="conteudo">
                    <a href="@Url.Action("FormatadorDeEmailMarketing", "Ferramentas")" class="text-uppercase">Formatador de E-mail Marketing</a>
                </div>
            </div>
        </div>
    </div>
</section>

ProgramadorFajuto.View/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-9">
                <div class="conteudo">
                    <a href="@Url.Action("ComoRecortarEmailMarketing", "Posts")" class="text-uppercase">Como Recortar E-mail Marketing</a>
                </div>
            </div>
            <div class="col-lg-3">
                <img src="~/images/gif_1.gif" class="img-responsive" />
            </div>
            <div class="col-lg-3 col-lg-offset-9">
                <img src="~/images/capivara.png" class="img-responsive" />
            </div>
        </div>
    </div>
</section>

ProgramadorFajuto.View/Views/Posts/ComoRecortarEmailMarketing.cshtml
@{
    ViewData["Title"] = "Como Recortar E-mail Marketing";
}

<div class="container">
    <div class="conteudo">
        <h3 class="text-center text-uppercase">como recortar e-mail marketing</h3>
        <p>Antes de tudo, abandone toda sua esperança e conhecimento em padrões web.</p>
        <p>Recorte a imagem no PSD que te mandaram, fazendo sempre cortes voltados para colunas, nunca linhas. Se você criar apenas um ROWSPAN que for acabou seu layout.</p>
    </div>
</div>

ProgramadorFajuto.View/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Programador Fajuto</title>

    <environment names="Development">
        <link rel="icon" type="image/png" sizes="16x16" href="~/favicon.ico">
        <link rel="stylesheet" href="~/lib/normalize-css/normalize.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />

        <link href="~/lib/toastr/css/toastr.css" rel="stylesheet" />
        
        <link rel="stylesheet" href="~/components/AnimatedBorderMenus/css/icons.css" />
        <link rel="stylesheet" href="~/components/AnimatedBorderMenus/css/style2.css" />

        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="icon" type="image/png" sizes="16x16" href="~/favicon.ico">
        <link rel="stylesheet" href="~/lib/normalize-css/normalize.css" />
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />

        <link href="~/lib/toastr/css/toastr.css" rel="stylesheet" />

        <link rel="stylesheet" href="~/components/AnimatedBorderMenus/css/icons.css" />
        <link rel="stylesheet" href="~/components/AnimatedBorderMenus/css/style2.css" />

        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav id="bt-menu" class="bt-menu">
        <a href="#" class="bt-menu-trigger"><span>Menu</span></a>
        <ul>
            <li><a href="@Url.Action("Index", "Home")" class="bt-icon icon-home">Home</a></li>
            <li><a href="@Url.Action("Index", "Ferramentas")" class="glyphicon glyphicon-wrench">Refresh</a></li>
        </ul>
    </nav>
    <div class="body-content">
        @RenderBody()
    </div>


    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

        <script src="~/lib/toastr/js/toastr.js"></script>

        <script src="~/components/AnimatedBorderMenus/js/classie.js"></script>
        <script src="~/components/AnimatedBorderMenus/js/borderMenu.js"></script>

        <script src="~/js/Geral.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>

        <script src="~/lib/toastr/js/toastr.js"></script>

        <script src="~/components/AnimatedBorderMenus/js/classie.js"></script>
        <script src="~/components/AnimatedBorderMenus/js/borderMenu.js"></script>

        <script src="~/js/Geral.js" asp-append-version="true"></script>
    </environment>

    @Html.Partial("_Mensagens")
    @RenderSection("scripts", required: false)
</body>
</html>

ProgramadorFajuto.View/Views/Shared/_Mensagens.cshtml
@if (TempData["MensagemDeSucesso"] != null)
{
    <script>
        var mensagem = "@TempData["MensagemDeSucesso"]";
        ProgramadorFajutoGeral.AdicionarMensagemDeSucesso(mensagem);
    </script>
}

@if (TempData["MensagemDeErro"] != null)
{
    <script>
        var mensagem = "@TempData["MensagemDeErro"]";
        ProgramadorFajutoGeral.AdicionarMensagemDeErro(mensagem);
    </script>
}